I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/mainpia.rpy", line 40, in script
    macname "hehe"
Exception: Sayer 'macname' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/mainpia.rpy", line 40, in script
    macname "hehe"
  File "D:\fanbase_project\KTPVisualNovel\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "D:\fanbase_project\KTPVisualNovel\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\fanbase_project\KTPVisualNovel\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'macname' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
KTPVisualNovel 1.0
Wed Mar 13 12:11:10 2024
