I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/pia/truepia.rpy", line 1820, in script
    show pia_date_talk at pia
Exception: Character expects its what argument to be a string, got <renpy.display.image.ImageReference object ('pia_date_talk',) at 0x000000000717c910>.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/pia/truepia.rpy", line 1820, in script
    show pia_date_talk at pia
  File "D:\fanbase_project\KTPVisualNovel\renpy\ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\fanbase_project\KTPVisualNovel\renpy\ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "D:\fanbase_project\KTPVisualNovel\renpy\exports.py", line 751, in show
    img = i(img) # type: ignore
  File "D:\fanbase_project\KTPVisualNovel\renpy\character.py", line 1305, in __call__
    raise Exception("Character expects its what argument to be a string, got %r." % (what,))
Exception: Character expects its what argument to be a string, got <renpy.display.image.ImageReference object ('pia_date_talk',) at 0x000000000717c910>.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
WGV:Dreamcatcher 
Mon Jul 29 14:36:19 2024
