I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/maintono.rpy", line 7, in script
    "mama" "oke, sekarang mandi, sarapan, abis itu langsung ke stasiun ya buat ke Jeketi University buat daftar ulang."
Exception: Sayer 'mama' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/maintono.rpy", line 7, in script
    "mama" "oke, sekarang mandi, sarapan, abis itu langsung ke stasiun ya buat ke Jeketi University buat daftar ulang."
  File "D:\fanbase_project\KTPVisualNovel\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "D:\fanbase_project\KTPVisualNovel\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\fanbase_project\KTPVisualNovel\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'mama' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
KTPVisualNovel 1.0
Mon Mar 11 16:50:30 2024
