I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/eksperimen.rpy", line 19, in script
    if previous_choice == "Bad End A":
  File "game/eksperimen.rpy", line 19, in <module>
    if previous_choice == "Bad End A":
NameError: name 'previous_choice' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/eksperimen.rpy", line 19, in script
    if previous_choice == "Bad End A":
  File "D:\fanbase_project\KTPVisualNovel\renpy\ast.py", line 1842, in execute
    if renpy.python.py_eval(condition):
  File "D:\fanbase_project\KTPVisualNovel\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\fanbase_project\KTPVisualNovel\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/eksperimen.rpy", line 19, in <module>
    if previous_choice == "Bad End A":
NameError: name 'previous_choice' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
WGV:Dreamcatcher 
Wed May  8 21:38:22 2024
